faceidnazorat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView,LoginView,LogoutView, EmployeeDetailView,AddEmployeeView,delete_employee,mobile,capture_view,kelish_ketish,capture_view_ketish,nazorat_mobile,nazorat_jadvali_date,EditProfilView,AdminProfilView,ish_vaqtlari

urlpatterns = [
    path('',HomeView.as_view(), name="home"),
    # path('upload/',upload_image, name="upload_image"),
    path('login/',LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(), name="logout"),
    path('admin_settings/<int:pk>/', AdminProfilView.as_view(), name='admin_settings'),
    path('ish_vaqtlari/', ish_vaqtlari , name='ish_vaqtlari'),


    # path('admin_settings/',AdminSettingsView.as_view(),name='admin_settings'),
    path('employee_detail/<int:pk>',EmployeeDetailView.as_view(),name='employee_detail'),
    path('delete_employee/<int:pk>',delete_employee,name='delete_employee'),
    path('add_employee/',AddEmployeeView.as_view(),name='add_employee'),
    # For mobile users
    path('mobile/',mobile,name='mobile'),
    path('kelish_ketish/',kelish_ketish,name='kelish_ketish'),
    path('capture/', capture_view, name='capture_view'),
    path('capture_ketish/', capture_view_ketish, name='capture_view_ketish'),
    path('nazorat_mobile/', nazorat_mobile, name='nazorat_mobile'),
    path('nazorat_jadvali_date/<str:i>/', nazorat_jadvali_date, name='nazorat_jadvali_date'),
     path('profil_setting/<int:pk>/', EditProfilView.as_view(), name='profil_setting'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Users(AbstractUser):
    position = models.CharField(max_length=30)
    phone = models.CharField(max_length=30, null=True)
    image = models.ImageField(upload_to='images/users')
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

class Kelish(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.date}"

class Ketish(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.date}"
    

class Ish_vaqti(models.Model):
    ishkelish = models.TimeField()
    ishketish = models.TimeField()

templates/admin_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Hokimiyat</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body style="background-color:#191C24; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
    
        <nav>

          <div class="" style=" color: white;   box-shadow: 0 0 10px black; display: flex; justify-content: space-between; align-items: center; height: 70px; margin: 10px; " >
          
            <a href="/" style="text-decoration: none; color: white;">
              <p style="font-size: 30px; margin-left: 10px;">HOKIMIYAT</p>
            </a>
                <a href="/profil_setting/{{ user.id }}/" style="margin-right: 10px; text-decoration: none;">
                  <div class="" style="display: flex; justify-content: center; align-items: center;">
                    <img class="img-xs rounded-circle" src="{{ user.image.url }}" style="width: 50px; height: 50px; border-radius: 100%;" alt="">
                    <p style="color: white; margin-left: 20px; font-size: 15px;">{{ user.first_name }}</p>
                  </div>
                </a>
          </div>
        </nav>
      </div>
      {% load crispy_forms_tags %}
      <div class="container" style=" margin: 30px 30px;  color: white;">
        <img src="{{ user.image.url }}" style="width: 200px; height: 200px;" >
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {{ form|crispy }}
    
            <button class="btn btn-success" type="submit">
                {{ button_title }}
            </button>
        </form>
    </div>

<script src="/static/js/bootstrap.js"></script>
</body>
</html>

templates/index.html
{% extends 'wrapper.html' %}

{% block content %}
<div class="row ">
  <div class="col-12 grid-margin">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title" style="display: flex;  align-items: center;">Xodimlar
          <a href='add_employee/' style="color: white; font-size: 20px; margin-left: 20px;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
          </svg></a>
          <form  name="search" style="display: flex; margin: 0 20px;" method="post">
            {% csrf_token %}
            <input type="text" class="form-control" placeholder="Search employee" name="searchuser" style="color: white;">
            <button type="submit" style="background: none; border: none; color: white; margin: 0 10px;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
            </svg>
          </button>
          </form>
          {% if employee != users %}
          <a href="/" style="color: white;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace" viewBox="0 0 16 16">
            <path d="M5.83 5.146a.5.5 0 0 0 0 .708L7.975 8l-2.147 2.146a.5.5 0 0 0 .707.708l2.147-2.147 2.146 2.147a.5.5 0 0 0 .707-.708L9.39 8l2.146-2.146a.5.5 0 0 0-.707-.708L8.683 7.293 6.536 5.146a.5.5 0 0 0-.707 0z"/>
            <path d="M13.683 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-7.08a2 2 0 0 1-1.519-.698L.241 8.65a1 1 0 0 1 0-1.302L5.084 1.7A2 2 0 0 1 6.603 1zm-7.08 1a1 1 0 0 0-.76.35L1 8l4.844 5.65a1 1 0 0 0 .759.35h7.08a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1z"/>
          </svg></a>
          {% endif %}
        </h4>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>
                  <div class="form-check form-check-muted m-0">
                    <label class="form-check-label">
                      <input type="checkbox" class="form-check-input" id="check-all">
                    </label>
                  </div>
                </th>
                <th> Rasm </th>
                <th> Username </th>
                <th> Ism </th>
                <th> Familiya </th>
                <th> Tel raqam </th>
                <th> Lavozimi </th>
                
              </tr>
            </thead>
            <tbody>
              {% for i in employees %}
              <tr>
                <td>
                  <div class="form-check form-check-muted m-0">
                    <label class="form-check-label">
                      <input type="checkbox" class="form-check-input checkbox-item">
                    </label>
                  </div>
                </td>
                  <td>
                    {% if i.image %}
                        <img src="{{ i.image.url }}" alt="image" />
                    {% endif %}
                </td>
                <td>
                  <span class="pl-2">{{ i.username }}</span>
                </td>
                <td> {{ i.first_name }} </td>
                <td> {{ i.last_name }} </td>
                <td> {{ i.phone }} </td>
                <td> {{ i.position }} </td>
                <td><a href="/employee_detail/{{ i.id }}" style="color: green;" class="badge badge-outline-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                        </svg></a>
                        <a href="/delete_employee/{{ i.id }}" style="color: green; margin-left: 10px;" class="badge badge-outline-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                          <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                        </svg></a>

                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
document.getElementById('check-all').addEventListener('change', function() {
    var checkboxes = document.querySelectorAll('.checkbox-item');
    checkboxes.forEach(function(checkbox) {
        checkbox.checked = this.checked;
    }, this);
});
</script>

{% endblock content %}

templates/ish_vaqtlari.html
{% extends 'wrapper.html' %}

{% block content %}
<div class="row ">
  <div class="col-12 grid-margin">
   
    </div>
  </div>

<script>
document.getElementById('check-all').addEventListener('change', function() {
    var checkboxes = document.querySelectorAll('.checkbox-item');
    checkboxes.forEach(function(checkbox) {
        checkbox.checked = this.checked;
    }, this);
});
</script>

{% endblock content %}

templates/kelish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face ID Capture</title>
</head>
<body style="background-color:#191C24; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">
    
    <h1 style="text-align: center;">Yuzni tasdiqlash</h1>
    <div id="message" style="text-align: center; color: red; font-weight: 400;"></div>
    <div class="container" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <video id="video" width="400" height="350" autoplay></video>
        <button id="capture" style="width: 100px; height: 30px; border: none; outline: none; border-radius: 2.5px; background: white;">Jonatish</button>
        <canvas id="canvas" width="400" height="350" style="display:none;"></canvas>
    </div>
    <script>
        // Access the camera and stream the video to the video element
        const video = document.getElementById('video');
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(stream => {
                video.srcObject = stream;
            })
            .catch(err => {
                console.error("Error accessing the camera: ", err);
            });

        // Capture the image and send it to the server
        const captureButton = document.getElementById('capture');
        captureButton.addEventListener('click', () => {
            const canvas = document.getElementById('canvas');
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);
            canvas.toBlob(blob => {
                const formData = new FormData();
                formData.append('image', blob, 'capture.png');

                fetch('/capture/', {
                    method: 'POST',
                    body: formData,
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                    window.location.href = data.redirect_url;
                    } 
                    else {
                        document.getElementById('message').textContent = data.message;
                    }
            })
            }, 'image/png');
        });
    </script>
</body>
</html>

templates/kelish_ketish.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Hokimiyat</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body style="background-color:#191C24; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
    
        <nav>

          <div class="" style=" color: white;   box-shadow: 0 0 10px black; display: flex; justify-content: space-between; align-items: center; height: 70px; margin: 10px; " >
          
              <a href="/mobile/" style="text-decoration: none; color: white;">
                <p style="font-size: 30px; margin-left: 10px;">HOKIMIYAT</p>
              </a>
                <a href="/profil_setting/{{ user.id }}/" style="margin-right: 10px; text-decoration: none;">
                  <div class="" style="display: flex; justify-content: center; align-items: center;">
                    {% if user.image and user.image.name %}
                    <img class="img-xs rounded-circle" src="{{ user.image.url }}" style="width: 50px; height: 50px; border-radius: 100%;" alt="">
                    {% endif %} 
                    <p style="color: white; margin-left: 20px; font-size: 15px;">{{ user.first_name }}</p>
                  </div>
                </a>
          </div>
        </nav>
      </div>

    <div class="container" style=" margin-top: 20px; display: flex; flex-wrap: wrap; justify-content: space-around;">
    <div class="kelish" style="width: 40%; height: 100px; border: 1px solid beige; margin: 10px 10px; ">
        <a href="/capture/" style="color: white; text-decoration: none; display: flex; flex-direction: column; justify-content: center; align-items: center;">  
            <i class="bi bi-box-arrow-in-right" style="font-size: 30px; margin-top: 10px;"></i>
            <p>Kelish</p>
        </a>
    </div>
    <div class="" style="width: 40%; height: 100px; border: 1px solid beige; margin: 10px 10px;">
        <a href="/capture_ketish/" style="color: white; text-decoration: none; display: flex; flex-direction: column; justify-content: center; align-items: center;">
            <i class="bi bi-box-arrow-left" style="font-size: 30px; margin-top: 10px;"></i>
            <p>Ketish</p>
        </a>
    </div>
    <div class="message" style="color: red; font-size: 30px; text-align: center;">{{message}}</div>
    
    </div>
    <div class="info" style="color: white;  width: 100%; display: flex; flex-direction: column; align-items: center;">
          <h2>Ish vaqtlari</h2>
          <h3>Kelish - 08:00</h3>
          <h3>Ketish - 16:00</h3>
      </div>

<script src="/static/js/bootstrap.js"></script>
</body>
</html>

templates/ketish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face ID Capture</title>
</head>
<body style="background-color:#191C24; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">
    
    <h1 style="text-align: center;">Yuzni tasdiqlash</h1>
    <div id="message" style="text-align: center; color: red; font-weight: 400;"></div>
    <div class="container" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
        <video id="video" width="400" height="350" autoplay></video>
        <button id="capture" style="width: 100px; height: 30px; border: none; outline: none; border-radius: 2.5px; background: white;">Jonatish</button>
        <canvas id="canvas" width="400" height="350" style="display:none;"></canvas>
    </div>
    <script>
        // Access the camera and stream the video to the video element
        const video = document.getElementById('video');
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(stream => {
                video.srcObject = stream;
            })
            .catch(err => {
                console.error("Error accessing the camera: ", err);
            });

        // Capture the image and send it to the server
        const captureButton = document.getElementById('capture');
        captureButton.addEventListener('click', () => {
            const canvas = document.getElementById('canvas');
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);
            canvas.toBlob(blob => {
                const formData = new FormData();
                formData.append('image', blob, 'capture.png');

                fetch('/capture_ketish/', {
                    method: 'POST',
                    body: formData,
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                    window.location.href = data.redirect_url;
                    } 
                    else {
                        document.getElementById('message').textContent = data.message;
                    }
            })
            }, 'image/png');
        });
    </script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face ID Capture</title>
</head>
<body style="background-color:#191C24; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: white;">
  {% for i in message %}
    <h1>{{ i }}</h1>
  {% endfor %}
    <h1>Face ID Capture</h1>
    <video id="video" width="400" height="350" autoplay></video>
    <button id="capture" >Capture</button>
    <canvas id="canvas" width="400" height="350" style="display:none;"></canvas>
    <script>
        // Access the camera and stream the video to the video element
        const video = document.getElementById('video');
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(stream => {
                video.srcObject = stream;
            })
            .catch(err => {
                console.error("Error accessing the camera: ", err);
            });

        // Capture the image and send it to the server
        const captureButton = document.getElementById('capture');
        captureButton.addEventListener('click', () => {
            const canvas = document.getElementById('canvas');
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);
            canvas.toBlob(blob => {
                const formData = new FormData();
                formData.append('image', blob, 'capture.png');

                fetch('/capture/', {
                    method: 'POST',
                    body: formData,
                })
                .then(response => response.json())
                .then(data => {
                    console.log('Success:', data);
                })
                .catch(error => {
                    console.error('Error:', error);
                });
            }, 'image/png');
        });
    </script>
</body>
</html>

templates/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login</title>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #000000;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }
    .container {
        width: 80%;
        max-width: 400px;
        background-color: #191C24;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        color: #fff;
    }
    h2 {
        text-align: center;
        margin-bottom: 20px;
    }
    input[type="text"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
    input[type="submit"] {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #4caf50;
        color: #fff;
        cursor: pointer;
    }
    input[type="submit"]:hover {
        background-color: #45a049;
    }
</style>
</head>
<body>

<div class="container">
    <h2>Login</h2>
    <span style="color: red;">{{ message }}</span>
    <form action="/login/" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <input type="submit" value="Login">
    </form>
</div>

</body>
</html>

templates/mobile.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Hokimiyat</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body style="background-color:#191C24; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
    
        <nav>

          <div class="" style=" color: white;   box-shadow: 0 0 10px black; display: flex; justify-content: space-between; align-items: center; height: 70px; margin: 10px; " >
          
                <p style="font-size: 30px; margin-left: 10px;">HOKIMIYAT</p>
                <a href="/profil_setting/{{ user.id }}/" style=" text-decoration: none;">
                  <div class="" style="display: flex; justify-content: center; align-items: center;">
                    {% if user.image and user.image.name %}
                    <img class="img-xs rounded-circle" src="{{ user.image.url }}" style="width: 50px; height: 50px; border-radius: 100%;" alt="">
                    {% endif %}
                    <p style="color: white; margin-left: 20px; font-size: 15px;">{{ user.first_name }}</p>
                    </div>
                    </a>
                  <a href="/logout/" style="margin-right: 20px; color: white; text-decoration: none; font-size: 25px;"><i class="bi bi-box-arrow-in-right"></i></a>
          </div>
        </nav>
      </div>
    <div class="container" style=" margin-top: 20px; display: flex; justify-content: space-around;">
    <div class="kelish" style="width: 40%; height: 100px; border: 1px solid beige; margin: 10px 10px; ">
        <a href="/kelish_ketish/" style="color: white; text-decoration: none; display: flex; flex-direction: column; justify-content: center; align-items: center;">  
            <i class="bi bi-box-arrow-in-right" style="font-size: 30px; margin-top: 10px;"></i>
            <p>Kelish-ketish</p>
        </a>
    </div>
    <div class="ketish" style="width: 40%; height: 100px; border: 1px solid beige; margin: 10px 10px;">
        <a href="/nazorat_mobile/" style="color: white; text-decoration: none; display: flex; flex-direction: column; justify-content: center; align-items: center;">
            <i class="bi bi-table" style="font-size: 30px; margin-top: 10px;"></i>
            <p>Nazorat jadvali</p>
        </a>
    </div>

    </div>

<script src="/static/js/bootstrap.js"></script>
</body>
</html>

templates/update_employee.html
{% extends 'wrapper.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <style>
        #id_name {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
        #id_surname {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
        #id_position {
            margin-top: 10px;
            margin-bottom: 30px;
            background-color: #191C24;
            color: white;

        }
        #id_phone {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
        #id_tg_id {
            margin-top: 10px;
            margin-bottom: 30px;
            color: white;

        }
    </style>
        <!-- Content Start -->
        <div class="content">
            <div class="forform" style="width: 95%;   background-color: #191C24; margin: 50px auto; box-sizing: border-box; padding: 50px;">
                {% load crispy_forms_tags %}
            <form action="" method="post" style="width: 50%; margin: 50px auto;  padding: 20px; box-sizing: border-box;color: white;" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{ form|crispy}}
                
                <button class="btn btn-success" type="submit">
                    Submit
                </button>
            </form>
           
        </div>


            
{% endblock content %}